project:
  type: website

website:
  title: "introduction à git et gitlab"
  sidebar:
    left:
    search: true
    contents:
      - index.qmd
      - chap1_commandes_base_git.qmd
      - chap2_cle_ssh.qmd
      - chap3_envoi_vers_forge.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    from: markdown+emoji
    code-tools: true
    code-overflow: wrap
    css: styles.css
    toc: true
  

glossary:
  path: glossary.yml
  popup: hover
  show: true
    
bibliography: biblio/biblio.bib
csl: biblio/nature.csl

