pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r _site/* .public/  # Copy only the contents of _site, not the folder itself
    - mv .public public
  artifacts:
    paths:
      - public/  # Serve the entire public directory as root
  only:
    - main
